language: node_js
node_js:
  - node
script:
  - npm install -g documentation
  - documentation build api.js --project-name "SinusBot Scripting Engine v2" -f html -o out
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: out
branches:
    only:
    - master
