language: node_js
node_js:
- node
script:
- npm install -g documentation jsdoc
- documentation build api.js --project-name "SinusBot Scripting Engine" -f html -o out
- sed -f after_building.sed -i out/index.html
- jsdoc -c config.json || true
- node generate.js
- cp tsd/types.d.ts out
deploy:
  - provider: pages
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
    local-dir: out
  - provider: npm
    email:
      secure: GBOh+TKTCfMd2/2zaullR5G/QbXlSSKBI7GPWV5QM5PR640gLmwgx9AzQUMvHZCkFIibeKtE48nuVK6HdburAA42kvkuBjQe3buHVVD7FU6FySnX96F2ZRx+SQoAUSeO/DRrTkHpMLyJRauLEM8yNsf/PICoiBpHnh8TK//ssZlI59hvDqEtg3D0lafEKLkfeQjVlqu9y+trBwhPd4DZquZKsfDbU4NpKuxZnQ4iVgW4XLS3LuZ4X3g5PDH+aWutWacpTrMLo5rCJhj6nKxlTGOhPfpkLbcSsDkY+BWUJ8qR/Hn7NSLkAmcDDuJS7KXeP0QvWeMYusxbqmlbl5+HY0SbZ+k5AGT9FfAjXhMIxmxcIU+8Ch+DomFe1i468IY3AmN3hpZXDoCCsYLentgY/xwUkUzv7haMS8y6XaAq90+jCqupyvkY52ms4Vl3NpRWvAhpEKrYnx609PZZBlY3fT7u68ayiuoda3damiQsNjNO7zM5AqJ3vzeDZTsmmOdlR9VPzgSiWfzEKCrSfw/VCkMzB+qs6vqeZNOxVZsjsRBUJZ5koFE09EsCRj0hrkXc1HMCBTz+SY/qGX3KbE13vMrICOAUi5eSJHd1d7DN3YzbMj7bbMmnDAXGMHWsBURtqrtvnwWkeOEk5m2kZ7glOV9qz+Z5lzLsC5oqtpdzosk=
    api_key:
      secure: TSpSpNN+JsiNRpMsLSBQLTS7Dp4XKqDexWBC/sh/4FBTJy4aafTtgKVR1+YyLD8z8wzsVt01Nl4o2RFw2JYgRClYKqeXWl789bMYxNtPc9Z+v/1Rc0EsAZbKq+xihmN35IbaYu2xHLGGFGbM2ltBdqMF026v2HjPqNKkgVy28Dhapsrsr2upRy+uS1flvlvBrZxL0KsBjBwbiDfPKSs6k1RJkXc0tj/P+GISmUVLu9CA8bYRoH38fCY6C4px2JseBkyhtuGFjTf4vLevI5se8AoTBMKdfc11LW/OTcewyXQx8mgLnxI7QJW9ZeW2UlL/LT4DxC+Bq7x/UQJSApNzCQ2luaxfa9b9K2D7FwboKYVQ4aYiwA7NMV7Ri+FapCPA6to1s9VaO/vXKaP4RsRTcaMlB992IA2IIwDYwU7MibGn0FfVe6IB9eLpIT5qebzGxkNHd6Aqwq2+5M/ZpKzzMBi+Fay9U5OYAl1z1SZts6cXVkRK352dqcurJQrBuP3gHVXSUgcDzGZ3NzqzuQdkfxL7idnMv1XX5D4kI2oK3Ucl0lmSUd4O3tzvezAnOAqajyR4SwHSFWM3+hP1eWMZXbclx1PyOHzkUfO/m03DXzhQCbpyRc4X+BxgVOYVKR5pRHPa0uKkROsUV8yzzFx63byNUF8KeJefdIYAzStfcqM=
    on:
      tags: true
      repo: SinusBot/scripting-docs
      branch: master
    skip_cleanup: true
branches:
  only:
  - master
